import type { ExplainResponse } from '@/lib/api/types';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function exportExplanationToPDF(explanation: ExplainResponse, narrative?: string) {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(18);
  doc.text('Explanation Report', 14, 20);

  // Summary
  doc.setFontSize(12);
  doc.text(`Target: ${explanation.target}`, 14, 35);
  doc.text(`Value: ${explanation.final_value.toFixed(4)}`, 14, 42);
  doc.text(`Confidence: ${(explanation.confidence * 100).toFixed(1)}%`, 14, 49);
  doc.text(`Missing Impact: ${(explanation.missing_impact * 100).toFixed(1)}%`, 14, 56);
  doc.text(`Hash: ${explanation.metadata.deterministic_hash.substring(0, 16)}...`, 14, 63);
  doc.text(`Created: ${new Date(explanation.metadata.created_at).toLocaleString()}`, 14, 70);

  // Breakdown table
  doc.setFontSize(14);
  doc.text('Breakdown', 14, 85);

  autoTable(doc, {
    startY: 90,
    head: [['Component', 'Value', 'Weight', 'Contribution', 'Percentage', 'Confidence']],
    body: explanation.breakdown.map(b => [
      b.label,
      b.value.toFixed(4),
      b.weight.toFixed(4),
      b.absolute_contribution.toFixed(4),
      `${b.percentage.toFixed(1)}%`,
      `${(b.confidence * 100).toFixed(1)}%`,
    ]),
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246] },
  });

  // Top Drivers
  const finalY = (doc as unknown as Record<string, { finalY?: number }>).lastAutoTable?.finalY || 150;
  doc.setFontSize(14);
  doc.text('Top Drivers', 14, finalY + 15);

  autoTable(doc, {
    startY: finalY + 20,
    head: [['Rank', 'Driver', 'Impact']],
    body: explanation.top_drivers.map(d => [
      `#${d.rank}`,
      d.name,
      d.impact.toFixed(4),
    ]),
    theme: 'grid',
    headStyles: { fillColor: [59, 130, 246] },
  });

  // Narrative (if provided)
  if (narrative) {
    const narY = (doc as unknown as Record<string, { finalY?: number }>).lastAutoTable?.finalY || 200;
    doc.setFontSize(14);
    doc.text('Narrative', 14, narY + 15);
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(narrative, 180);
    doc.text(lines, 14, narY + 25);
  }

  // Footer
  doc.setFontSize(8);
  doc.text(`Generated by Explainable Engine | ${new Date().toISOString()}`, 14, 285);

  doc.save(`explanation-${explanation.id.substring(0, 8)}.pdf`);
}
